pipeline {
    agent any
    stages {
         stage('Clean Workspace'){
        steps {
          cleanWs()
          }
      }
        stage ('Checkout') {
            steps {
                checkout scm
              }
            }          

        stage('Version node') {
            steps {
               echo "Version node"
               bat "node -v"
            }
        }
        stage('Install Newman') {
            steps {
                echo "install bootstrap"
                sh "npm install -g bootstrap@4.0.0-alpha.6"
                echo "install newman"
                sh "npm install -g newman"
                echo "install reporter htmlextra"
                sh "npm install -g newman-reporter-htmlextra"
                echo "install newman-reporter-allure"
                sh "npm install -g newman-reporter-htmlextra"
            }
        }
        stage('Tests') {
            steps {
                 echo "Run tests"
                 sh "newman run postman/test.postman_collection.json"
            }
        }

    }
}
