version: '3.7'

services:
  postman_checks:
    image: postman/newman:ubuntu
    container_name: tests
    command : 
       run test.postman_collection.json    
    volumes:
      - ./postman:/etc/newman     
