name: ASI/API Tests

on:
  push:
    branches: [ main ]
#   schedule:
#       - cron:  '30 5,17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install newman
        run: |
          npm install -g bootstrap@4.0.0-alpha.6
          npm install -g newman
          npm install -g newman-reporter-allure
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: | 
          mkdir -p TestResults
          mkdir -p allure-results
      - name: Run collection
        if: always()
        run: |
          newman run "postman/BloomApi.postman_collection.json" --reporters cli,allure,htmlextra --reporter-allure-export allure-results --reporter-htmlextra-export TestResults/HtmlReport.html
      - name: Tests results Allure
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
        if: always()
      - name: Tests results TestResults
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults
        if: always()
      - name: Send Results and Generate Allure Report
        uses: Xotabu4/send-to-allure-server-action@1
        if: always()
        with:
          allure-server-url: 'http://allureserver.com:5001/'
