name: ASI/API Tests

on:
 push:
   branches: [ main ]
#   schedule:
#       - cron:  '30 5,17 * * *'

jobs:
 build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
      node-version: [16]
   steps:
   - uses: actions/checkout@v3

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - name: Install newman
     run: |
       npm install -g bootstrap@4.0.0-alpha.6
       npm install -g newman
       npm install -g newman-reporter-htmlextra
       npm install -g newman-reporter-allure
   - name: Make Directory for results
     run: mkdir -p testResults
   - name: Run collection
     if: always()
     run: |
         newman run "postman/BloomApi.postman_collection.json" -r htmlextra --reporter-htmlextra-export ./testResults/report_Bloom_uat.html -r allure --reporter-allure-export ./allure/
         
   - name: Tests results
     uses: actions/upload-artifact@v3
     with:
        name: RunReports
        path: testResults
     if: always()
